### PR TITLE
Add Bootstrap for Responsive Web

### PR DESCRIPTION
**Pull request by hyunjun529**
1. Bootstrap compiled LibSass, and it's customized.
2. legacy style.css was named style_old.css.
3. Bootstrap version is 3.3.7.

### CODE REVIEW

**Comment by hyunjun529** [comment]
i find the ui bug
register : input tag "username"

**Comment by InhoChoi** [comment]
- Make the position of sidebar fixed on left-side
- Sidebar Menu have to be capital letter

**Comment by hyunjun529** [comment]
please check update

**Comment by devholic** [comment]
Please merge into develop branch :(

**Pull request closed without merging**
